[package]
name = "cedar-hypertext"
version = "0.1.0"
authors = ["Tom Schroeder <j.tom.schroeder@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
quote = "0.4"
syn = "0.12"
proc-macro2 = "0.2"
failure = "0.1"
