[package]
name = "cargo-cedar"
version = "0.1.0"
authors = ["Tom Schroeder <j.tom.schroeder@gmail.com>"]

[dependencies]
#quicli = "0.2"
structopt = { version = "0.2", default-features = false }
hammer = { path = "../../hammer" }
